# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 365)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.name = QtWidgets.QLabel(self.centralwidget)
        self.name.setGeometry(QtCore.QRect(10, 10, 191, 20))
        self.name.setObjectName("name")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(210, 10, 281, 141))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lab1but = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.lab1but.setObjectName("lab1but")
        self.gridLayout.addWidget(self.lab1but, 0, 0, 1, 1)
        self.lab2but = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.lab2but.setObjectName("lab2but")
        self.gridLayout.addWidget(self.lab2but, 1, 0, 1, 1)
        self.lab3but = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.lab3but.setObjectName("lab3but")
        self.gridLayout.addWidget(self.lab3but, 2, 0, 1, 1)
        self.lab4but = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.lab4but.setObjectName("lab4but")
        self.gridLayout.addWidget(self.lab4but, 3, 0, 1, 1)
        self.lab5but = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.lab5but.setObjectName("lab5but")
        self.gridLayout.addWidget(self.lab5but, 4, 0, 1, 1)
        self.lab6but = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.lab6but.setObjectName("lab6but")
        self.gridLayout.addWidget(self.lab6but, 0, 1, 1, 1)
        self.lab7but = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.lab7but.setObjectName("lab7but")
        self.gridLayout.addWidget(self.lab7but, 1, 1, 1, 1)
        self.lab8but = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.lab8but.setObjectName("lab8but")
        self.gridLayout.addWidget(self.lab8but, 2, 1, 1, 1)
        self.lab9but = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.lab9but.setObjectName("lab9but")
        self.gridLayout.addWidget(self.lab9but, 3, 1, 1, 1)
        self.lab10but = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.lab10but.setObjectName("lab10but")
        self.gridLayout.addWidget(self.lab10but, 4, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.name.setText(_translate("MainWindow", "Субботин Д.А ИС 22/9-П"))
        self.lab1but.setText(_translate("MainWindow", "ЛАБ 1"))
        self.lab2but.setText(_translate("MainWindow", "ЛАБ 2"))
        self.lab3but.setText(_translate("MainWindow", "ЛАБ 3"))
        self.lab4but.setText(_translate("MainWindow", "ЛАБ 4"))
        self.lab5but.setText(_translate("MainWindow", "ЛАБ 5"))
        self.lab6but.setText(_translate("MainWindow", "ЛАБ 6"))
        self.lab7but.setText(_translate("MainWindow", "ЛАБ 7"))
        self.lab8but.setText(_translate("MainWindow", "ЛАБ 8"))
        self.lab9but.setText(_translate("MainWindow", "ЛАБ 9"))
        self.lab10but.setText(_translate("MainWindow", "ЛАБ 10"))
